kind: Deployment
apiVersion: apps/v1
metadata:
   name: sample-project2
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: project2
   template:
      metadata:
        labels:
          app: project2
      spec:
       containers:
        - name: sample-project2
          image: prashanth2paramaah/project2
          imagePullPolicy: Always
          ports:
          - containerPort: 80
