kind: Service                             
apiVersion: v1
metadata:
  name: sample-project2
  labels:
    app: project2
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: project2                    
  type: LoadBalancer                   
